pipeline {
	agent {
		docker {
			image 'composer:latest'
		}
	}
	stages {
		stage('Build') {
			steps {
                            // Change to the specified directory and run Composer to install dependencies
                            dir('jenkins-phpunit-test') {
                            sh 'composer install'
                         }
			}
			}
		}
		stage('Test') {
			steps {
                sh './vendor/bin/phpunit tests'
            }
		}
	}
}
