pipeline {
    agent {
        docker {
            image 'composer:latest'
        }
    }
    stages {
        stage('Build') {
            steps {
                // Change to the specified directory and run Composer to install dependencies
                dir('jenkins-phpunit-test') {
                    sh 'composer install'
                }
            }
        }
        stage('Test') {
            steps {
        dir('jenkins-phpunit-test') { // Ensure you're in the correct directory
            sh './vendor/bin/phpunit tests'
        }
        }
    }
}

